"""FastAPI app exposing the Graph-RAG pipeline as a public endpoint.

Interactive docs are auto-generated by FastAPI at /docs and /redoc.

Auth: intentionally none. This is a public portfolio demo meant to be
clicked and tried without a key; a per-IP rate limiter (rate_limit.py)
guards the free-tier LLM/DB quotas instead. Add real auth before pointing
this at anything beyond a demo.
"""

import logging
import sys

from fastapi import Depends, FastAPI
from fastapi.middleware.cors import CORSMiddleware
from groq import Groq
from pydantic import BaseModel

from src.api.rate_limit import rate_limit
from src.api.stats import record, snapshot
from src.config import GROQ_API_KEY
from src.generation.generator import generate_answer
from src.retrieval.pipeline import retrieve
from src.routing.router import route

# A dedicated handler/formatter on our own logger only — not logging.basicConfig(),
# which would configure the root logger and mangle every third-party library's
# plain-text log lines (uvicorn, groq, neo4j, ...) into invalid JSON by forcing
# them through a formatter built for our own structured messages.
logger = logging.getLogger("graph_rag")
logger.setLevel(logging.INFO)
logger.propagate = False
_handler = logging.StreamHandler(sys.stdout)
_handler.setFormatter(logging.Formatter('{"time":"%(asctime)s","level":"%(levelname)s","msg":%(message)s}'))
logger.addHandler(_handler)

app = FastAPI(
    title="Graph-RAG API",
    description="Hybrid graph + vector RAG with complexity-based model routing.",
    version="0.1.0",
)
# Public demo endpoint — open CORS so it's callable from any frontend origin.
# Tighten allow_origins to a specific list before handling non-demo traffic.
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"],
)
_client = Groq(api_key=GROQ_API_KEY)


class AskRequest(BaseModel):
    question: str
    use_graph: bool = True
    use_routing: bool = True


class AskResponse(BaseModel):
    answer: str
    model: str
    tier: str
    latency_seconds: float
    complexity_score: float
    cypher: str | None
    graph_facts_count: int
    vector_chunks_count: int


@app.get("/health")
def health() -> dict:
    return {"status": "ok"}


@app.get("/stats")
def stats() -> dict:
    return snapshot()


@app.post("/ask", response_model=AskResponse, dependencies=[Depends(rate_limit)])
def ask(request: AskRequest) -> AskResponse:
    retrieval = retrieve(_client, request.question, use_graph=request.use_graph)
    decision = route(request.question, use_routing=request.use_routing)
    result = generate_answer(_client, decision, request.question, retrieval["context"])

    record(result.tier, result.latency_seconds)
    logger.info(
        '{"question_len":%d,"use_graph":%s,"use_routing":%s,"tier":"%s","model":"%s",'
        '"complexity_score":%.3f,"latency_seconds":%.3f,"graph_facts_count":%d,"vector_chunks_count":%d}',
        len(request.question),
        str(request.use_graph).lower(),
        str(request.use_routing).lower(),
        result.tier,
        result.model,
        decision.score,
        result.latency_seconds,
        len(retrieval["graph_rows"]),
        len(retrieval["vector_chunks"]),
    )

    return AskResponse(
        answer=result.answer,
        model=result.model,
        tier=result.tier,
        latency_seconds=result.latency_seconds,
        complexity_score=decision.score,
        cypher=retrieval["cypher"],
        graph_facts_count=len(retrieval["graph_rows"]),
        vector_chunks_count=len(retrieval["vector_chunks"]),
    )
