"""FastAPI app exposing the Graph-RAG pipeline as a public endpoint.

Interactive docs are auto-generated by FastAPI at /docs and /redoc.
"""

from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from groq import Groq
from pydantic import BaseModel

from src.config import GROQ_API_KEY
from src.generation.generator import generate_answer
from src.retrieval.pipeline import retrieve
from src.routing.router import route

app = FastAPI(
    title="Graph-RAG API",
    description="Hybrid graph + vector RAG with complexity-based model routing.",
    version="0.1.0",
)
# Public demo endpoint — open CORS so it's callable from any frontend origin.
# Tighten allow_origins to a specific list before handling non-demo traffic.
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"],
)
_client = Groq(api_key=GROQ_API_KEY)


class AskRequest(BaseModel):
    question: str
    use_graph: bool = True
    use_routing: bool = True


class AskResponse(BaseModel):
    answer: str
    model: str
    tier: str
    latency_seconds: float
    complexity_score: float
    cypher: str | None
    graph_facts_count: int
    vector_chunks_count: int


@app.get("/health")
def health() -> dict:
    return {"status": "ok"}


@app.post("/ask", response_model=AskResponse)
def ask(request: AskRequest) -> AskResponse:
    retrieval = retrieve(_client, request.question, use_graph=request.use_graph)
    decision = route(request.question, use_routing=request.use_routing)
    result = generate_answer(_client, decision, request.question, retrieval["context"])

    return AskResponse(
        answer=result.answer,
        model=result.model,
        tier=result.tier,
        latency_seconds=result.latency_seconds,
        complexity_score=decision.score,
        cypher=retrieval["cypher"],
        graph_facts_count=len(retrieval["graph_rows"]),
        vector_chunks_count=len(retrieval["vector_chunks"]),
    )
